name: BuildIt
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # теперь применимо ко всему job

    steps:
      - name: "Clone source"
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Setup MSVC"
        uses: ilammy/msvc-dev-cmd@v2

      - name: "Build"
        run: |
          mkdir build
          cd build
          cmake -G "NMake Makefiles" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER=clang-cl \
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded ..
          cmake --build .

      - name: "Package"
        run: |
          7z a cslol-patcher.zip build/cslol-*
          7z rn cslol-patcher.zip build/ cslol-patcher/
        shell: bash

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: cslol-patcher
          path: cslol-patcher.zip
          retention-days: 15
