name: BuildIt
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  # разрешаем старым actions работать на Node.js 20

    steps:
      - name: "Clone source"
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: "Setup MSVC"
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: "Build DLL"
        run: |
          mkdir -p build
          cd build
          cmake -G "NMake Makefiles" \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER=clang-cl \
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded ..
          cmake --build .

          # Проверяем, что DLL реально существует
          if [ ! -f cslol-dll.dll ]; then
            echo "ERROR: cslol-dll.dll не найден!"
            exit 1
          fi
        shell: bash

      - name: "Package DLL"
        run: |
          7z a cslol-patcher.zip build/cslol-*
          7z rn cslol-patcher.zip build/ cslol-patcher/
        shell: bash

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: cslol-patcher
          path: cslol-patcher.zip
          retention-days: 15
